"""bidirectional relationship observation x monitoringsession

Revision ID: 1bcdaa8aca2e
Revises: 4bc06eec89df
Create Date: 2026-07-22 12:51:19.013069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1bcdaa8aca2e'
down_revision: Union[str, Sequence[str], None] = '4bc06eec89df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('monitoring_session_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'observations', 'monitoring_sessions', ['monitoring_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.drop_column('observations', 'monitoring_session_id')
    # ### end Alembic commands ###
