"""revert any bidirectionality for now. add divesite to monitoring session

Revision ID: 312f8756af16
Revises: 1bcdaa8aca2e
Create Date: 2026-07-22 18:05:16.676443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '312f8756af16'
down_revision: Union[str, Sequence[str], None] = '1bcdaa8aca2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_sessions', sa.Column('dive_site', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_sessions', 'dive_site')
    # ### end Alembic commands ###
