"""bidirectional relationship observation x monitoringsession

Revision ID: 75b0695be4f9
Revises: 954fd3b17146
Create Date: 2026-07-22 12:42:55.782363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '75b0695be4f9'
down_revision: Union[str, Sequence[str], None] = '954fd3b17146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('observations_monitoring_session_id_fkey'), 'observations', type_='foreignkey')
    op.drop_column('observations', 'monitoring_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('monitoring_session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('observations_monitoring_session_id_fkey'), 'observations', 'monitoring_sessions', ['monitoring_session_id'], ['id'])
    # ### end Alembic commands ###
