"""add minotoring name

Revision ID: 954fd3b17146
Revises: 960df9ec1513
Create Date: 2026-07-22 12:18:34.222915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '954fd3b17146'
down_revision: Union[str, Sequence[str], None] = '960df9ec1513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_sessions', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_sessions', 'name')
    # ### end Alembic commands ###
