"""remove crop polygon from observation, instead save crop image path

Revision ID: 960df9ec1513
Revises: cf9cda8ba19b
Create Date: 2026-07-17 10:05:50.557968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '960df9ec1513'
down_revision: Union[str, Sequence[str], None] = 'cf9cda8ba19b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('cropped_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('observations', 'crop_polygon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('crop_polygon', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('observations', 'cropped_image_path')
    # ### end Alembic commands ###
