"""try fixing observations <> monitoring sessions relationship

Revision ID: cf9cda8ba19b
Revises: 40c92a7b9ac1
Create Date: 2026-07-17 00:28:44.354795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9cda8ba19b'
down_revision: Union[str, Sequence[str], None] = '40c92a7b9ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
